/*Project Euler: Problem 44: Pentagon numbers
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimized; what is the value of D?*/


function pentagonNumbers() {
  var notFound=true;
  var i=1;
  var result=0;
  while(notFound){
    i++;
    var n = i * (3 * i - 1) / 2;
    for (let j = i-1; j > 0; j--) {
        let m = j * (3 * j - 1) / 2;
        if (isPenta(n - m) && isPenta(n + m)) {
            result = n-m;
            notFound = false;
            break;
        }
    }
  };
  return result;
}

function isPenta(num){
  return Number.isInteger((Math.sqrt(1 + 24 * num) + 1) / 6);
}


console.log(pentagonNumbers());