/*Project Euler: Problem 45: Triangular, pentagonal, and hexagonal
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle
Tn=n(n+1)/2
1, 3, 6, 10, 15, ...
Pentagonal
Pn=n(3n−1)/2
1, 5, 12, 22, 35, ...
Hexagonal
Hn=n(2n−1)
1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.*/

/*Un número Hexagonal es a la fuerza Triangular, así que solo hay que comparar Hexagonales con Pentagonales*/

function triPentaHexa(n) {
  var result = 0;
  var i = 143;
 
  while (true) {
    i++;
    result = i * (2 * i - 1);
 
    if (isPenta(result)) {
        break;
    }
  }
  return result;
}

function isPenta(num){
  return Number.isInteger((Math.sqrt(1 + 24 * num) + 1) / 6);
}

//triPentaHexa(40756);


console.log(triPentaHexa(40756));
